name: Say Hello World
on:
  issues:
    types:
      - opened
  pull_request:

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      - uses: SaemJeon/deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}